#!/usr/bin/env python3
"""Keep the no-toolchain web installer identical to the tested implementation."""
import pathlib, sys
root = pathlib.Path(__file__).resolve().parents[1]
header = '#!/bin/zsh\n# Generated by scripts/generate-installer.py.\nset -euo pipefail\n'
body = (root / 'scripts/lib/install-dmg.sh').read_text()
footer = '\ndoorbell_install_from_dmg_url "${DOORBELL_DMG_URL:-https://github.com/vagdotdev/doorbell/releases/latest/download/Doorbell.dmg}"\n'
expected = header + body + footer
out = root / 'web/install.sh'
if '--check' in sys.argv:
    if out.read_text() != expected: sys.exit('web/install.sh is out of date; run scripts/generate-installer.py')
else: out.write_text(expected)
