#!/usr/bin/env zsh
# Wire the local Doorbell stack: client .env, Convex deployment secrets, auth keys, seed, tests, bundle.
#
#   scripts/setup-local.sh          # full setup
#   scripts/setup-local.sh --quick  # env + convex only (skip tests/bundle)
#
# Needs: npm install, `npm run dev` already running on :3210
set -euo pipefail
cd "$(dirname "$0")/.."

QUICK=false
[[ "${1:-}" == "--quick" ]] && QUICK=true

load_env() {
  local file=$1
  [[ -f "$file" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" != *"="* ]] && continue
    local key="${line%%=*}"
    local val="${line#*=}"
    key="${key#"${key%%[![:space:]]*}"}"
    key="${key%"${key##*[![:space:]]}"}"
    val="${val#"${val%%[![:space:]]*}"}"
    val="${val%"${val##*[![:space:]]}"}"
    val="${val%\"}"; val="${val#\"}"
    val="${val%\'}"; val="${val#\'}"
    [[ -z "$key" ]] && continue
    export "$key=$val"
  done < "$file"
}

[[ -f .env.secrets ]] || {
  echo "Missing .env.secrets — copy .env.secrets.example and fill LiveKit + join secret." >&2
  exit 1
}

load_env .env.local
load_env .env.secrets

CONVEX_URL="${CONVEX_URL:-http://127.0.0.1:3210}"
JOIN="${DOORBELL_JOIN_SECRET:-doorbell}"

# Client config (bundled into the app — no LiveKit secrets).
cat > .env <<EOF
# Generated by scripts/setup-local.sh — safe to edit DOORBELL_BACKEND / CONVEX_URL.
DOORBELL_BACKEND=convex
CONVEX_URL=${CONVEX_URL}
DOORBELL_JOIN_SECRET=${JOIN}
EOF
echo "→ .env"

# Server secrets → Convex deployment only.
for key in LIVEKIT_URL LIVEKIT_PUBLIC_URL LIVEKIT_API_KEY LIVEKIT_API_SECRET; do
  val="${(P)key:-}"
  if [[ -z "$val" ]]; then
    echo "Missing $key in .env.secrets" >&2
    exit 1
  fi
  npx convex env set "${key}=${val}" >/dev/null
  echo "→ Convex $key"
done

node scripts/convex-auth-keys.mjs

if [[ "${SEED_DEMO:-}" == "1" ]]; then
  echo "→ seed demo friends (SEED_DEMO=1)"
  DOORBELL_JOIN_SECRET="$JOIN" CONVEX_URL="$CONVEX_URL" python3 scripts/seed-friends.sh
else
  echo "→ skip demo seed (set SEED_DEMO=1 to add @priya / @arjun)"
fi

if $QUICK; then
  echo "ok (quick)"
  exit 0
fi

echo "→ tests"
npx tsc --noEmit
npx vitest run
swift test

echo "→ bundle"
scripts/bundle.sh debug

echo ""
echo "Ready."
echo "  Convex dashboard: http://127.0.0.1:6790/"
echo "  LiveKit cloud:    ${LIVEKIT_PUBLIC_URL}"
echo "  App:              open build/Doorbell.app"
echo "  Join as @vagdev:  DOORBELL_JOIN=Vagdev:vagdev open build/Doorbell.app"
